{"uuid": "3a9acd98-755f-476e-b595-3469c9da5a60", "children": ["652b6794-5507-41a2-8f1d-73949158fbe3"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.0.108', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002D778677820>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))\n", "trace": "  File \"C:\\Users\\User\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\otus-oP12gESo-py3.10\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\User\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\otus-oP12gESo-py3.10\\lib\\site-packages\\_pytest\\fixtures.py\", line 1128, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\User\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\otus-oP12gESo-py3.10\\lib\\site-packages\\_pytest\\fixtures.py\", line 907, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\projects\\OTUS\\lesson30_scrin\\conftest.py\", line 45, in browser\n  File \"C:\\Users\\User\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\otus-oP12gESo-py3.10\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 288, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\User\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\otus-oP12gESo-py3.10\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 381, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"C:\\Users\\User\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\otus-oP12gESo-py3.10\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 442, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"C:\\Users\\User\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\otus-oP12gESo-py3.10\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 294, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"C:\\Users\\User\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\otus-oP12gESo-py3.10\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 316, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"C:\\Users\\User\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\otus-oP12gESo-py3.10\\lib\\site-packages\\urllib3\\request.py\", line 78, in request\n    return self.request_encode_body(\n  File \"C:\\Users\\User\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\otus-oP12gESo-py3.10\\lib\\site-packages\\urllib3\\request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"C:\\Users\\User\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\otus-oP12gESo-py3.10\\lib\\site-packages\\urllib3\\poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"C:\\Users\\User\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\otus-oP12gESo-py3.10\\lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\User\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\otus-oP12gESo-py3.10\\lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\User\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\otus-oP12gESo-py3.10\\lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\User\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\otus-oP12gESo-py3.10\\lib\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"C:\\Users\\User\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\otus-oP12gESo-py3.10\\lib\\site-packages\\urllib3\\util\\retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1673021664408, "stop": 1673021730064}], "start": 1673021664408, "stop": 1673021730432}